$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$main = Get-Content (Join-Path $root "src/main.cpp") -Raw
$workerLifecycle = Get-Content (Join-Path $root "src/worker_lifecycle.h") -Raw
$workerLifecycleImpl = Get-Content (Join-Path $root "src/worker_lifecycle.cpp") -Raw
$diag = Join-Path $root "out\diagnostics\startup.txt"
function Require-Text($text, $needle, $message) { if (-not $text.Contains($needle)) { Write-Error $message } }
Require-Text $workerLifecycle "enum class WorkerLifecycleReason" "worker lifecycle reason enum is missing"
Require-Text $main "appendWorkerLifecycleEvent" "worker lifecycle event helper is missing"
Require-Text $main "WorkerLifecycleReason::StartRequested" "start reason is missing"
Require-Text $main "WorkerLifecycleReason::RestartBlocked" "restart blocked reason is missing"
Require-Text $main "WorkerLifecycleReason::StaleHeartbeatKill" "stale kill reason is missing"
Require-Text $main "WorkerLifecycleReason::ForcedTerminate" "forced termination reason is missing"
Require-Text $main "WorkerLifecycleReason::GpuInitFailed" "GPU init failure reason is missing"
Require-Text $main "WorkerLifecycleReason::InteropFailed" "interop failure reason is missing"
Require-Text $main "WorkerLifecycleReason::RenderFailed" "render failure reason is missing"
Require-Text $main "invalidateDisplayedCudaFrame()" "scene/reset path must invalidate stale displayed CUDA frames"
Require-Text $main "g_d3d.activeDisplaySimSlot = -1" "display slot state must be cleared on scene/reset invalidation"
Require-Text $main "g_lastCopiedWorkerSequence = 0" "scene/reset invalidation must not advance the copy cursor past the first new-scene worker frame"
Require-Text $main "clearSimulationFrame(g_simFrame)" "scene/reset invalidation must clear stale fire pixels"
Require-Text $main "stopCudaWorker()" "scene switch must restart the worker boundary"
Require-Text $main "invalidateSharedViewportPublishedFrames()" "scene switch must clear stale shared CUDA frame publication metadata"
Require-Text $main "clearHostSharedFrameHandles()" "scene switch must close stale host-opened shared CUDA textures"
Require-Text $main "g_sharedViewport->latestFrameSlot = -1" "scene switch invalidation must clear latest shared frame slot"
Require-Text $main "g_sharedViewport->sharedTextureHandleValues[slot] = 0" "scene switch invalidation must clear shared texture handles"
Require-Text $main "slotSceneEpochs[kSharedFrameSlots]" "shared frame slots must carry scene epochs"
Require-Text $main "activeSceneEpoch" "shared viewport must expose active scene epoch"
Require-Text $main "slotEpoch != g_sceneEpoch" "host copy path must reject stale scene slots"
Require-Text $main "epochB == g_sceneEpoch" "host copy candidate must re-check scene epoch after acquiring the keyed mutex"
Require-Text $main "sequence > g_lastCopiedWorkerSequence" "host copy path must identify stale ready slots behind the copy cursor"
Require-Text $main "D3D stale shared frame drain" "host copy path must drain stale keyed-mutex slots back to the worker"
Require-Text $main "g_sharedViewport->workerHeartbeatTickMs = 0" "worker restart must clear stale heartbeat telemetry before launching a new worker"
Require-Text $main "g_sharedViewport->lastFrameTickMs = 0" "worker restart must clear stale frame timestamps before launching a new worker"
Require-Text $main "heartbeatBelongsToCurrentWorker" "watchdog must ignore stale heartbeat ticks from a previous worker generation"
Require-Text $main "g_sharedViewport->workerHeartbeatTickMs >= g_sharedViewport->workerStartTickMs" "watchdog must bind heartbeat freshness to the current worker start tick"
Require-Text $main "g_sharedViewport->activeSceneEpoch = settings.sceneEpoch" "worker settings/publish path must write the canonical scene epoch"
Require-Text $main "g_sharedViewport->slotSceneEpochs[publishSlot] = settings.sceneEpoch" "worker publish path must stamp every shared slot with the scene epoch"
Require-Text $main "const LONG sceneEpoch = settings.sceneEpoch > 0 ? settings.sceneEpoch : g_sceneEpoch" "worker must preserve host-authored scene epoch instead of overwriting it with worker-local epoch"
Require-Text $main "refreshSceneInstance(scene, sceneEpoch)" "scene instance refresh must use the settings epoch"
Require-Text $main "sceneFrameEpochContract=each shared CUDA texture slot carries the canonical scene epoch and stale scene frames are rejected before copy/present" "diagnostics scene frame epoch contract is missing from source"
Require-Text $workerLifecycleImpl "worker-lifecycle:%s" "worker event prefix is missing"
Require-Text $main "workerLifecycleReasons=start-requested,createprocess-failed,restart-blocked,stale-heartbeat-kill,stop-requested,forced-terminate,exited,gpu-init-failed,interop-failed,render-failed,clean-exit" "diagnostics worker lifecycle string is missing from source"
if (Test-Path $diag) {
    $diagText = Get-Content $diag -Raw
    Require-Text $diagText "workerLifecycleEvents=worker-lifecycle:<reason> entries in out/worker-events.log" "diagnostics do not report lifecycle event contract"
}
Write-Host "worker lifecycle gate ok"
