$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "verify-helpers.ps1")

$sceneRuntime = Read-RepoText "src/scene_runtime.h"
$cuda = Read-RepoText "src/fire_cuda.cu"
$main = Read-RepoText "src/main.cpp"
$labels = Read-RepoText "src/ui_labels.h"
$capture = Read-RepoText "scripts/capture-scene-set.ps1"
$productScene = Read-RepoText "scripts/verify-product-scene-work.ps1"

Require-Text $sceneRuntime "constexpr int kSceneCount = 1;" "runtime must expose exactly one product scene"
Require-Text $sceneRuntime "constexpr int kProductSceneId = 0;" "product scene id must be the only runtime scene id"
Require-Text $sceneRuntime "constexpr bool kProductRuntimeSceneLocked = true;" "product runtime scene lock is missing"
Require-Text $sceneRuntime 'constexpr const char* kProductSceneKey = "methanol-pool";' "product scene key must be methanol-pool"
Require-Text $main "settings.sceneId = kProductSceneId;" "canonical settings must force the product scene"
Require-Text $main "g_activeScene = kProductSceneId;" "interactive startup must force the product scene"
Require-Text $main "g_focusSceneMode = true;" "interactive product runtime must run in focus-scene mode"
Require-Text $main "drawSceneButton(pixels, kProductSceneButtonRect" "UI must draw only the product scene button"
Require-Text $main "const int nextScene = kProductSceneId" "product scene requests must clamp to the product scene"
Require-Text $main "Product scene locked: NIST methanol" "S-key product scene request must stay locked"
Require-Text $main "productSceneIsolation=interactive and desktop runtime expose only the NIST methanol product scene" "diagnostics must report scene isolation"
Require-Text $main "sceneSourceModels=NIST methanol 1m liquid pool product path" "diagnostics must report the product source model"
Require-Text $labels 'return "NIST Methanol";' "scene button label must expose the product scene"
Require-Text $cuda "constexpr int kProductSceneId = 0;" "CUDA product path must know the only scene id"
Require-Text $cuda "(void)settings.sceneId;" "CUDA step path must ignore caller scene ids"
Require-Text $cuda "params.sceneId = kProductSceneId;" "CUDA step path must force the product scene"
Require-Text $cuda "(void)settings.sceneSourceMode;" "CUDA source path must ignore caller source-mode switches"
Require-Text $cuda "params.sceneSourceMode = 3;" "CUDA source path must force methanol pool source mode"
Require-Text $main "void loadSceneEmitters() {" "product emitter loading seam is missing"
Require-Text $main "g_sceneEmitters[kProductSceneId] = loadSceneEmitterParams(kProductSceneId);" "runtime must load only the product emitter"
Require-Text $main "settings.sceneId = kProductSceneId;" "placement and emitter application must force the product scene"
Require-Text $main "sceneCameraProfile(kProductSceneId)" "camera profile must ignore stale scene ids during product bring-up"
Require-Text $capture '@{ Name = "nist-methanol-pool"; Id = 0 }' "capture set must only target the product scene"
Require-Text $productScene "productSceneWork = `$true" "scene work verifier must be product-scene scoped"
Forbid-Text $main "settings.sceneId == 2" "non-product branch leaked back into the product viewport"
Forbid-Text $main "for (int scene = 0; scene < kSceneCount; ++scene) {" "runtime must not iterate scene variants during product bring-up"
Forbid-Text $cuda "sceneSourceMode == 2" "non-product source branch leaked back into the CUDA product path"
Forbid-Text $cuda "gasBurnerPort" "non-product source helper leaked back into the CUDA product path"

Write-Host "product scene isolation gate ok"
