$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "verify-helpers.ps1")
$root = Split-Path -Parent $PSScriptRoot
$main = Read-RepoText "src/main.cpp"
$sharedViewport = Get-Content (Join-Path $root "src/shared_viewport.h") -Raw
$runtimeHealth = Get-Content (Join-Path $root "src/runtime_health.h") -Raw
$workerLifecycle = Get-Content (Join-Path $root "src/worker_lifecycle.h") -Raw
$workerLifecycleImpl = Get-Content (Join-Path $root "src/worker_lifecycle.cpp") -Raw
$diag = Join-Path $root "out\diagnostics\startup.txt"
Require-Text $workerLifecycle "enum class WorkerLifecycleReason" "worker lifecycle reason enum is missing"
Require-Text $main "appendWorkerLifecycleEvent" "worker lifecycle event helper is missing"
Require-Text $main "WorkerLifecycleReason::StartRequested" "start reason is missing"
Require-Text $main "WorkerLifecycleReason::RestartBlocked" "restart blocked reason is missing"
Require-Text $main "WorkerLifecycleReason::StaleHeartbeatKill" "stale kill reason is missing"
Require-Text $main "WorkerLifecycleReason::ForcedTerminate" "forced termination reason is missing"
Require-Text $main "WorkerLifecycleReason::GpuInitFailed" "GPU init failure reason is missing"
Require-Text $main "WorkerLifecycleReason::InteropFailed" "interop failure reason is missing"
Require-Text $main "WorkerLifecycleReason::RenderFailed" "render failure reason is missing"
Require-Text $main "invalidateDisplayedCudaFrame()" "scene/reset path must invalidate stale displayed CUDA frames"
Require-Text $main "g_d3d.activeDisplaySimSlot = -1" "display slot state must be cleared on scene/reset invalidation"
Require-Text $main "g_lastCopiedWorkerSequence = 0" "scene/reset invalidation must not advance the copy cursor past the first new-scene worker frame"
Require-Text $main "clearSimulationFrame(g_simFrame)" "scene/reset invalidation must clear stale fire pixels"
Require-Text $main "invalidateWorkerSceneEpochOnly()" "product-scene refresh must use the hot worker scene-epoch invalidation path"
Require-Text $main "g_haveLastWorkerSettings = false" "product-scene refresh must force fresh settings publication to the live worker"
Forbid-Text $main "startCudaWorker(false)" "product-scene refresh must not restart the worker before fresh scene settings are published"
Require-Text $main "const bool workerSceneChanged =" "worker must detect scene/epoch changes inside the live CUDA loop"
Require-Text $main "settings.reset = 1;" "worker scene changes must reset CUDA fields instead of hot-swapping profiles into stale simulation state"
Require-Text $main "g_resetFramesRemaining = 0" "interactive product-scene refresh must not queue a full CUDA reset transaction"
Forbid-Text $main "kInteractiveSceneCount" "interactive scene registry must stay locked to the product scene"
Require-Text $main "g_activeScene = kProductSceneId" "interactive product path must force the methanol scene"
Require-Text $main "Product scene locked: NIST methanol" "keyboard scene cycling must stay locked"
Require-Text $main "drawSceneButton(pixels, kProductSceneButtonRect" "scene UI must expose only the product selector"
Require-Text $main "const int nextScene = kProductSceneId" "product-scene request path must clamp to the product scene"
Require-Text $main "lastAppliedWorkerScene = settings.sceneId" "worker must remember the last scene it applied"
Require-Text $main "lastAppliedWorkerEpoch = settings.sceneEpoch" "worker must remember the last scene epoch it applied"
Require-Text $main "worker-settings-scene" "worker must log scene/epoch/reset state for desktop shortcut diagnosis"
Require-Text $main "g_sharedViewport->latestFrameSlot = -1" "product-scene invalidation must clear latest shared frame slot"
Require-Text $main "g_sharedViewport->sharedTextureHandleValues[slot] = 0" "product-scene invalidation must clear shared texture handles"
Require-Text $sharedViewport "slotSceneEpochs[kD3DSharedFrameSlots]" "shared frame slots must carry scene epochs"
Require-Text $sharedViewport "activeSceneEpoch" "shared viewport must expose active scene epoch"
Require-Text $main "slotEpoch != g_sceneEpoch" "host copy path must reject stale scene slots"
Require-Text $main "const bool staleEpoch = slotEpoch != g_sceneEpoch" "host copy path must explicitly drain stale-epoch keyed mutex slots"
Require-Text $main "(!staleEpoch && !alreadyCopied)" "host copy path must not strand stale scene slots at keyed-mutex key 1"
Require-Text $main "epochB == g_sceneEpoch" "host copy candidate must re-check scene epoch after acquiring the keyed mutex"
Require-Text $main "sequence > newestSequence" "host copy path must identify the newest current-epoch ready slot"
Require-Text $main "D3D stale shared frame drain" "host copy path must drain stale keyed-mutex slots back to the worker"
Require-Text $main "g_sharedViewport->workerHeartbeatTickMs = 0" "worker restart must clear stale heartbeat telemetry before launching a new worker"
Require-Text $main "g_sharedViewport->lastFrameTickMs = 0" "worker restart must clear stale frame timestamps before launching a new worker"
Require-Text $main "g_interactiveGpuKernelLaunchAllowed = gpuKernelLaunchAllowed(args)" "interactive worker launch must not bypass the GPU safety gate"
Require-Text $main "g_cudaWorkerRequested = workerDefaultRequested && g_interactiveGpuKernelLaunchAllowed" "default CUDA worker request must require explicit GPU risk acceptance"
Require-Text $main "CUDA worker safety-gated; explicit risk acceptance required" "safety-gated worker status is missing"
Require-Text $main "toggleInteractiveCudaWorker" "operator CUDA worker button must be wired to a single guarded toggle"
Require-Text $main "interactive-cuda-worker-button" "operator CUDA button must write a safety-stop reason when blocked"
Require-Text $main "CUDA LOCKED" "operator UI must expose the locked CUDA state"
Require-Text $main "drawNoLiveCudaViewport" "safety-gated or stale worker state must draw a visible non-black viewport"
Require-Text $main "CUDA WORKER BLOCKED BY SAFETY GATE" "no-live CUDA viewport must explain when safety gating blocked the worker"
Require-Text $main "heartbeatBelongsToCurrentWorker" "watchdog must ignore stale heartbeat ticks from a previous worker generation"
Require-Text $main "g_sharedViewport->workerHeartbeatTickMs >= g_sharedViewport->workerStartTickMs" "watchdog must bind heartbeat freshness to the current worker start tick"
Require-Text $main "CUDA worker restart pending" "watchdog must retry a requested worker when shared viewport state is not initialized"
Require-Text $main "g_sharedViewport->activeSceneEpoch = settings.sceneEpoch" "worker settings/publish path must write the canonical scene epoch"
Require-Text $main "g_sharedViewport->slotSceneEpochs[publishSlot] = settings.sceneEpoch" "worker publish path must stamp every shared slot with the scene epoch"
Require-Text $main "const LONG sceneEpoch = settings.sceneEpoch > 0 ? settings.sceneEpoch : g_sceneEpoch" "worker must preserve host-authored scene epoch instead of overwriting it with worker-local epoch"
Require-Text $main "refreshSceneInstance(scene, sceneEpoch)" "scene instance refresh must use the settings epoch"
Require-Text $main "sceneFrameEpochContract=each shared CUDA texture slot carries the canonical scene epoch and stale scene frames are rejected before copy/present" "diagnostics scene frame epoch contract is missing from source"
Require-Text $main "frameHealthStateName" "host UI must expose structured frame health, not only worker-alive state"
Require-Text $runtimeHealth "struct FrameHealthInput" "frame health classification must live outside main.cpp"
Require-Text $runtimeHealth "classifyFrameHealthState" "structured frame health classifier is missing"
Require-Text $runtimeHealth "classifyFireStreamHealthLabel" "fire-stream health classifier is missing"
Require-Text $main "currentFrameHealthInput()" "main.cpp must adapt telemetry into the runtime health seam"
Require-Text $workerLifecycleImpl "worker-lifecycle:%s" "worker event prefix is missing"
Require-Text $main "workerLifecycleReasons=start-requested,createprocess-failed,restart-blocked,stale-heartbeat-kill,stop-requested,forced-terminate,exited,gpu-init-failed,interop-failed,render-failed,clean-exit" "diagnostics worker lifecycle string is missing from source"
if (Test-Path $diag) {
    $diagText = Get-Content $diag -Raw
    Require-Text $diagText "workerLifecycleEvents=worker-lifecycle:<reason> entries in out/worker-events.log" "diagnostics do not report lifecycle event contract"
}
Write-Host "worker lifecycle gate ok"
