$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "verify-helpers.ps1")

$main = Read-RepoText "src/main.cpp"
$cuda = Read-RepoText "src/fire_cuda.cu"
$header = Read-RepoText "src/fire_cuda.h"
$cmake = Read-RepoText "CMakeLists.txt"
$profile = Read-RepoText "scripts/profile-cuda-kernels.ps1"
$manifestScript = Read-RepoText "scripts/write-cuda-artifact-manifest.ps1"
$diag = Join-Path $script:RepoRoot "out\diagnostics.txt"

Require-Text $header "struct FireCudaLaunchBudget" "CUDA launch budget contract is missing from the public runtime API"
Require-Text $header "bool fireCudaSetLaunchBudget" "runtime launch budget setter is missing"
Require-Text $header "bool fireCudaProfilerStart" "CUDA profiler capture-range API is missing"
Require-Text $header "stagingBytes" "CUDA diagnostics must expose staging allocation bytes"
Require-Text $cuda "g_volumeLaunchDepth" "volume launch depth must be a runtime budget, not a fixed compile-time constant"
Require-Text $cuda "g_renderLaunchRows" "render launch rows must be a runtime budget, not a fixed compile-time constant"
Require-Text $cuda "allocateDeviceBuffer" "device allocations must be accounted for by the VRAM budget tracker"
Require-Text $cuda "allocatePinnedHostBuffer" "pinned host staging allocator is missing"
Require-Text $cuda "cudaHostAlloc" "host staging must use pinned memory, not pageable frame copies"
Require-Text $cuda "NvtxRange" "NVTX timeline ranges are missing"
Require-Text $cuda "cudaProfilerStart" "CUDA profiler capture range start is missing"
Require-Text $cuda "cudaMemGetInfo" "CUDA diagnostics must report runtime VRAM state"
Require-Text $cuda "allocatedBytes" "CUDA diagnostics must expose tracked allocation bytes"
Require-Text $main "runCudaPreflight" "CUDA preflight command is missing"
Require-Text $main "runCudaSliceFinder" "CUDA slice-finder command is missing"
Require-Text $main "--cuda-slice-finder" "CUDA slice-finder CLI entrypoint is missing"
Require-Text $main "--cuda-preflight" "CUDA preflight CLI entrypoint is missing"
Require-Text $main "cudaPreflightArtifactFresh" "interactive CUDA launch must require a fresh preflight artifact"
Require-Text $main "g_cudaWorkerRequested = workerDefaultRequested && g_interactiveGpuKernelLaunchAllowed && g_cudaPreflightPassed" "default worker launch must require explicit risk acceptance and fresh CUDA preflight"
Require-Text $main "CUDA worker locked; run --cuda-preflight first" "UI must explain preflight lock state"
Require-Text $main '\"preflightOk\": ' "preflight report must emit pass/fail state"
Require-Text $main '\"interactiveLaunchAllowed\": ' "preflight report must explicitly authorize or reject interactive CUDA launch"
Require-Text $main '\"medianLaunchMs\": ' "preflight report must include median launch timing"
Require-Text $main '\"p95LaunchMs\": ' "preflight report must include p95 launch timing"
Require-Text $main '\"vramBudgetOk\": ' "preflight report must include VRAM budget status"
Require-Text $main '\"fieldValidityOk\": ' "preflight report must include field validity status"
Require-Text $main '\"abiOk\": ' "preflight report must include ABI/device compatibility status"
Require-Text $main '\"sliceFinderOk\": ' "slice-finder report must emit pass/fail state"
Require-Text $main '\"recommendedVolumeSliceDepth\": ' "slice-finder report must recommend volume slice depth"
Require-Text $main '\"recommendedRenderSliceRows\": ' "slice-finder report must recommend render slice rows"
Require-Text $main "cudaSliceFinderArtifact=out\\cuda-slice-finder\\slice-finder.json" "diagnostics must document slice-finder artifact"
Require-Text $main "cudaArtifactManifest=out\\cuda-artifact-manifest.json" "diagnostics must document CUDA artifact manifest"
Require-Text $main "cudaLaunchBudget=median<=800ms,p95<=1200ms,valid-fields,abi-ok,vram-budget-ok" "diagnostics must document the CUDA prevention gate"
Require-Text $cmake "86-real 89-real 90-real 90-virtual" "CUDA build must include native fatbin targets plus PTX fallback"
Require-Text $profile "NsightSystems" "CUDA profiling script must support Nsight Systems timeline capture"
Require-Text $profile "--capture-range=cudaProfilerApi" "Nsight Systems capture must be gated by cudaProfilerStart/Stop"
Require-Text $profile "SliceFinder" "CUDA profiling script must expose the slice-finder harness"
Require-Text $manifestScript "Get-FileHash -Algorithm SHA256" "CUDA artifact manifest must include artifact sha256"
Require-Text $manifestScript "nvidia-smi --query-gpu=driver_version,name" "CUDA artifact manifest must log driver ABI state"
Require-Text $manifestScript "nvidiaSmiBanner" "CUDA artifact manifest must capture nvidia-smi CUDA banner"
Require-Text $manifestScript "requiredImages" "CUDA artifact manifest must declare required fatbin images"
Forbid-Text $cuda "constexpr int kVolumeLaunchDepth = 256" "fixed monolithic volume launch depth was reintroduced"
Forbid-Text $cuda "constexpr int kRenderLaunchRows = 1024" "fixed monolithic render launch rows were reintroduced"

if (Test-Path $diag) {
    $diagText = Get-Content $diag -Raw
    Require-Text $diagText "cudaPreflightRequiredForInteractiveStart=true" "diagnostics do not report preflight requirement"
    Require-Text $diagText "cudaLaunchBudget=median<=800ms,p95<=1200ms,valid-fields,abi-ok,vram-budget-ok" "diagnostics do not report CUDA launch budget"
}

Write-Host "cuda prevention contract gate ok"
