$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "verify-helpers.ps1")

$main = Read-RepoText "src/main.cpp"
$cuda = Read-RepoText "src/fire_cuda.cu"
$registry = Read-RepoText "src/render_debug_modes.h"
$labels = Read-RepoText "src/ui_labels.h"
$launcher = Read-RepoText "launch-firesim.ps1"

Require-Text $registry "enum RenderDebugMode" "debug mode registry is missing"
Require-Text $registry "kRenderDebugGas" "GAS debug mode is missing from the registry"
Require-Text $registry "kRenderDebugFlow" "FLOW debug mode is missing from the registry"
Require-Text $registry "kRenderDebugSource" "SRC debug mode is missing from the registry"
Require-Text $registry "kRenderDebugOxygen" "OXY debug mode is missing from the registry"
Require-Text $registry "kRenderDebugActiveBricks" "active brick debug mode is missing from the registry"
Require-Text $registry "kRenderDebugSkippedBricks" "skipped brick debug mode is missing from the registry"
Require-Text $registry "kRenderDebugEmission" "emission debug mode is missing from the registry"
Require-Text $registry "kRenderDebugExtinction" "extinction debug mode is missing from the registry"
Require-Text $registry "kRenderDebugReaction" "reaction debug mode is missing from the registry"
Require-Text $registry "kRenderDebugProduct" "product debug mode is missing from the registry"
Require-Text $registry "nextRenderDebugMode" "debug-mode cycle is not centralized"
Require-Text $registry "renderDebugModeDiagnosticsList" "debug-mode diagnostics list is not centralized"
Require-Text $registry "renderDebugModeNeedsBrickProbe" "brick debug modes must use a named registry predicate"
Require-Text $labels "renderDebugModeShortName(mode)" "UI labels do not consume the debug-mode registry"
Require-Text $main "g_renderDebugMode = nextRenderDebugMode(g_renderDebugMode)" "debug-mode key cycle does not use the registry"
Require-Text $main 'g_renderDebugMode = argumentIntValue(args, "--debug-mode="' "interactive app must honor launcher debug mode"
Require-Text $main "renderDebugModeDiagnosticsList()" "diagnostics do not use the debug-mode registry"
Require-Text $cuda "clampRenderDebugMode(settings.renderDebugMode)" "CUDA settings clamp does not use the debug-mode registry"
Require-Text $cuda "debugGas" "CUDA renderer does not accumulate gas concentration"
Require-Text $cuda "debugFlowVector" "CUDA renderer does not accumulate gas flow direction"
Require-Text $cuda "debugSource" "CUDA renderer does not accumulate source mask"
Require-Text $cuda "debugOxygenSupply" "CUDA renderer does not accumulate oxygen supply"
Require-Text $cuda "fuelBedSource(wp.x, wp.z, fv, p)" "source debug view must use the same source mask as CUDA physics"
Require-Text $cuda "solidFuelBedMaterial(wp.x, wp.z, p)" "source debug view must expose the underlying fuel material mask"
Require-Text $cuda "renderDebugModeNeedsSourceProbe" "source debug mode must use a named registry predicate"
Require-Text $cuda "renderDebugModeNeedsVelocity" "flow debug mode must use a named registry predicate"
Require-Text $cuda "sparseRaymarchBrickProbe" "brick debug modes must inspect sparse brick metadata"
Require-Text $cuda "debugEmission" "CUDA renderer must expose emission debug accumulation"
Require-Text $cuda "debugExtinction" "CUDA renderer must expose extinction debug accumulation"
Require-Text $cuda "debugReaction" "CUDA renderer must expose reaction/progress debug accumulation"
Require-Text $cuda "debugProduct" "CUDA renderer must expose product/smoke debug accumulation"
Require-Text $launcher "plume-test" "launcher must expose the no-wind/no-turbulence plume diagnostic"
Require-Text $launcher "vertical-velocity" "launcher must expose vertical velocity inspection"
Require-Text $launcher '"--debug-mode=$debugMode"' "launcher must pass debug mode into the interactive app"

Write-Host "gas debug views gate ok"
