#pragma once

#include <cstdint>

struct FireCudaDiagnostics {
    int driverVersion = 0;
    int runtimeVersion = 0;
    int deviceCount = 0;
    int activeDevice = -1;
    int computeMajor = 0;
    int computeMinor = 0;
    std::uint64_t totalGlobalMem = 0;
    std::uint64_t freeGlobalMem = 0;
    std::uint64_t allocatedBytes = 0;
    std::uint64_t stagingBytes = 0;
    int volumeSliceDepth = 0;
    int renderSliceRows = 0;
    char deviceName[128] = {};
};

struct FireCudaLaunchBudget {
    int volumeSliceDepth = 32;
    int renderSliceRows = 180;
    float medianLaunchBudgetMs = 800.0f;
    float p95LaunchBudgetMs = 1200.0f;
    float vramBudgetFraction = 0.72f;
};

struct FireCudaFrameMetrics {
    int frameIndex = 0;
    int gridX = 0;
    int gridY = 0;
    int gridZ = 0;
    int pressureIterations = 0;
    int invalidCells = 0;
    float timeSeconds = 0.0f;
    float gpuSolveMs = 0.0f;
    float gpuRenderMs = 0.0f;
    float gpuVelocityMs = 0.0f;
    float gpuReactionMs = 0.0f;
    float gpuProjectionMs = 0.0f;
    float gpuLightingMs = 0.0f;
    float gpuRaymarchMs = 0.0f;
    float gpuPackMs = 0.0f;
    float heatSum = 0.0f;
    float fuelSum = 0.0f;
    float oxygenSum = 0.0f;
    float sootSum = 0.0f;
    float charSum = 0.0f;
    float ashSum = 0.0f;
    float pyrolysisSum = 0.0f;
    float progressSum = 0.0f;
    float turbulenceEnergySum = 0.0f;
    float sootOpticalDepthSum = 0.0f;
    float maxHeat = 0.0f;
    float maxFuel = 0.0f;
    float maxSoot = 0.0f;
    float maxPyrolysis = 0.0f;
    float maxProgress = 0.0f;
    float maxTurbulenceEnergy = 0.0f;
    float flameHeightMeters = 0.0f;
    float meanOpticalDepth = 0.0f;
    float meanSceneLight = 0.0f;
    float meanSceneShadow = 0.0f;
    float flameMassProxy = 0.0f;
    float smokeMassProxy = 0.0f;
    float flameSmokeOverlapProxy = 0.0f;
    float meanVolumetricShadow = 0.0f;
    float meanRoomIrradiance = 0.0f;
    float heatReleaseProxy = 0.0f;
    float divergenceBeforeL2 = 0.0f;
    float divergenceBeforeMax = 0.0f;
    float divergenceAfterL2 = 0.0f;
    float divergenceAfterMax = 0.0f;
    float divergenceReduction = 0.0f;
};

struct FireSettings {
    int width = 1280;
    int height = 720;
    float dt = 1.0f / 60.0f;
    float mouseX = 0.5f;
    float mouseY = 0.12f;
    int leftDown = 0;
    int rightDown = 0;
    int reset = 0;
    int showGizmos = 1;
    int activeGizmo = 1;
    int sceneId = 0;
    int sceneEpoch = 0;
    float wind = 0.0f;
    float turbulence = 0.72f;
    float detail = 0.88f;
    float smoke = 0.92f;
    float intensity = 1.0f;
    float cameraYaw = 0.0f;
    float cameraPitch = 0.18f;
    float cameraDistance = 3.35f;
    int cinematicMode = 0;
    int raymarchSteps = 56;
    int emberCount = 96;
    int renderDebugMode = 0;
    float exposure = 1.0f;
    float reflectionGain = 1.0f;
    float smokeDarkness = 1.0f;
    float emitterCenterX = 0.0f;
    float emitterCenterZ = 0.0f;
    float emitterHeightNorm = 0.0f;
    float emitterHeightBandNorm = 0.06f;
    float emitterRadius = 0.48f;
    int sceneSourceMode = 0;
    float sceneSourceHeightCeiling = 0.145f;
    float sceneCharScale = 1.0f;
    float sceneSootScale = 1.0f;
    float sceneInitialHeatBase = 0.86f;
    float sceneInitialHeatNoise = 0.24f;
    float sceneInitialFuelBase = 1.08f;
    float sceneInitialFuelNoise = 0.26f;
    float sceneInitialSoot = 0.018f;
    float sceneInitialAshScale = 1.0f;
    float sceneInitialPyrolysisBase = 0.058f;
    float sceneInitialPyrolysisNoise = 0.028f;
    float sceneInitialProgress = 0.21f;
    float sceneInitialTurbulence = 0.065f;
    float sceneInitialSootOptics = 0.018f;
    float sceneGasFeed = 0.0f;
    float scenePyrolysisGain = 1.0f;
    float sceneFuelGain = 1.0f;
    float sceneHeatGain = 1.0f;
    float sceneSootGain = 1.0f;
    float sceneCharGrowth = 0.026f;
    float sceneAshScale = 1.0f;
    float sceneBedHeatBase = 6.20f;
    float scenePyrolysisFuelScale = 3.70f;
    float scenePyrolysisSootScale = 1.0f;
    float sceneSootYieldScale = 1.0f;
    float sceneCurlScale = 1.0f;
    float sceneBuoyancyScale = 1.0f;
    float sceneBuoyancyCeiling = 0.96f;
    float sceneBuoyancyFloor = 0.08f;
    float sceneFloorGlowR = 0.55f;
    float sceneFloorGlowG = 0.11f;
    float sceneFloorGlowB = 0.023f;
    float sceneFloorTongueR = 0.46f;
    float sceneFloorTongueG = 0.070f;
    float sceneFloorTongueB = 0.014f;
    float sceneFloorGlowScale = 0.48f;
    float sceneFloorTongueScale = 0.14f;
    float sceneWallGlowR = 0.15f;
    float sceneWallGlowG = 0.050f;
    float sceneWallGlowB = 0.018f;
    float sceneWallGlowScale = 0.090f;
    float sceneOrangeEmissionScale = 3.10f;
    float sceneFilamentEmissionScale = 1.10f;
    float sceneWarmScatter = 0.30f;
    float sceneSmokeScale = 1.0f;
    float sceneSourcePlaneMode = 0.0f;
    float sceneBurnerJetScale = 0.0f;
    float sceneCampTongueScale = 0.0f;
    float sceneRoomTrayScale = 1.0f;
    float sceneConvectiveHeightTop = 0.88f;
    float sceneConvectiveHeightBottom = 0.030f;
    float sceneFlameHeightTop = 0.76f;
    float sceneFlameHeightBottom = 0.10f;
    float sceneLowerWhiteHeight = 0.060f;
    float sceneRoomCoverageBase = 0.72f;
    float sceneRoomCoverageScale = 1.24f;
    float sceneTopDissolveTop = 0.88f;
    float sceneTopDissolveBottom = 0.42f;
    float sceneCampHoleScale = 0.0f;
    float sceneCampTongueDensityScale = 0.0f;
    float sceneBlueEmissionScale = 0.0f;
    float sceneBlueJetEmissionScale = 0.0f;
    float sceneFlameColorR = 1.32f;
    float sceneFlameColorG = 0.27f;
    float sceneFlameColorB = 0.038f;
    float sceneAlternateFlameColorR = 1.52f;
    float sceneAlternateFlameColorG = 0.24f;
    float sceneAlternateFlameColorB = 0.028f;
    float sceneAlternateFlameColorScale = 0.0f;
    float sceneEmberRejectAbove = 1.01f;
    float sceneEmberLifeRateBase = 0.20f;
    float sceneEmberLifeRateJitter = 0.18f;
    float sceneEmberLifeRateAdd = 0.0f;
    float sceneEmberSpawnMode = 0.0f;
    float sceneEmberStartVBase = 0.045f;
    float sceneEmberStartVJitter = 0.0f;
    float sceneEmberLift = 0.80f;
    float sceneEmberLifeScale = 1.10f;
    float sceneEmberDrag = 1.35f;
    float sceneEmberRadiusBase = 0.00086f;
    float sceneEmberRadiusJitter = 0.00145f;
    float sceneEmberTrailCap = 0.005f;
    float sceneEmberHotR = 1.0f;
    float sceneEmberHotG = 0.42f;
    float sceneEmberHotB = 0.090f;
    float sceneEmberCoolR = 0.18f;
    float sceneEmberCoolG = 0.026f;
    float sceneEmberCoolB = 0.008f;
    float sceneEmberAlphaScale = 0.82f;
    int burnerCenterCount = 0;
    float burnerCenterX[4] = {};
    float burnerCenterY[4] = {};
    float burnerCenterZ[4] = {};
};

bool fireCudaInitialize(int frameWidth, int frameHeight, int gridWidth, int gridHeight);
bool fireCudaStepAndRender(std::uint32_t* bgraPixels, const FireSettings& settings);
bool fireCudaStepAndRenderMeasured(std::uint32_t* bgraPixels, const FireSettings& settings, FireCudaFrameMetrics* metrics);
bool fireCudaSelectDeviceForD3D11(void* d3d11Device);
bool fireCudaRegisterD3D11Texture(void* d3d11Texture);
bool fireCudaRegisterD3D11TextureSlot(int slot, void* d3d11Texture);
bool fireCudaSetD3D11TextureSlot(int slot);
bool fireCudaStepD3D11(const FireSettings& settings);
bool fireCudaStepAndRenderD3D11(const FireSettings& settings);
bool fireCudaStepAndRenderD3D11Measured(const FireSettings& settings, FireCudaFrameMetrics* metrics);
bool fireCudaRenderD3D11(const FireSettings& settings);
void fireCudaUnregisterD3D11Texture();
bool fireCudaSynchronize();
bool fireCudaReset();
bool fireCudaGetDiagnostics(FireCudaDiagnostics* diagnostics);
bool fireCudaSetLaunchBudget(const FireCudaLaunchBudget& budget);
bool fireCudaProfilerStart();
bool fireCudaProfilerStop();
void fireCudaShutdown();
const char* fireCudaLastError();
